In [1]:
#1) Write a program to create a 5 dimensional array with all zeros and ones

import numpy as np
b=np.ones((1,1,1,5,4),dtype=int)

In [7]:
b

array([[[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]]]])

In [8]:
a=np.zeros((1,1,1,5,4),dtype=int)

In [9]:
a

array([[[[[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]]]]])

In [10]:
#2) Write a program to create an array of 10 zeros,10 ones, and 10 fives in row 1 2 and 3 which create a new array of
#shape (3,10)

l=[]
a=np.arange(1,31).reshape(3,10)
for i in a.flatten():
    if(i<=10):
        l.append(0)
    elif(11<=i<=20):
        l.append(1)
    else:
        l.append(5)
x=np.array(l).reshape(3,10)
print(x)

[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [5 5 5 5 5 5 5 5 5 5]]


In [11]:
#3) Write a program to create a 3x4 matrix filled with values from 10 to 21.


np.arange(10,22).reshape(3,4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [12]:
#4) Write a  program to create a 10x10 zero matrix with elements on the main diagonal equal to 0,1,2,3,4,5,6,7,8,9.
l=[0,1,2,3,4,5,6,7,8,9]
np.diag(l)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [14]:
#5)Write a program to create a 4x4 array. Create an array from below array by swapping first and last, second and third columns

x=np.arange(1,17).reshape(4,4)
y=x[:,::-1]
print(x)
print()
print(y)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [15]:
#6) Write a program to reverse an array (the first element becomes the last).
#Given array:
#[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 ]


x=np.arange(12,28)
x[::-1]

array([27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

In [16]:
x=np.arange(12,28)
a=[]
for i in x:
    a.insert(0,i)
reverse=np.array(a)
print(reverse)
    
    

[27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]


In [17]:
type(reverse)

numpy.ndarray

In [18]:
#7) Write a program to access all the elements greater than 30 and less than 80 and multiples of 5 from an array of 
#shape 10,10 .Elements range from 1 to 100

x=np.arange(1,101).reshape(10,10)
y=(x%5==0) & (30<x) & (80>x)
x[y]


array([35, 40, 45, 50, 55, 60, 65, 70, 75])

In [21]:
#8) Write a program to create a 2D array with 1 on the border and 0 inside.


n=int(input("enter the no.of rows: "))
m=int(input("enter no.of colums: "))
x=np.zeros((n,m),dtype=int)
for i in x:
    x[0:1,:]=1
    x[-1:,:]=1
    x[:,0:1]=1
    x[:,-1:]=1
print(x)

enter the no.of rows: 5
enter no.of colums: 5
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [22]:
#9) Write a program to create a checkerboard pattern .Don't use default array function Checkerboard pattern:                    
#[[0 1 0 1 0 1 0 1]                                                      
# [1 0 1 0 1 0 1 0]                                                      
# [0 1 0 1 0 1 0 1]                                                      
# [1 0 1 0 1 0 1 0]                                                      
# [0 1 0 1 0 1 0 1]                                                      
# [1 0 1 0 1 0 1 0]                                                      
# [0 1 0 1 0 1 0 1]                                                      
# [1 0 1 0 1 0 1 0]]


l=[]
for i in range(0,64):
    a=i/8
    if(a%2==0):
        if(i%2==0):
            l.append(1)
        else:
            l.append(0)
    else:
        if(i%2==0):
            l.append(0)
        else:
            l.append(1)
            
x=np.array(l).reshape(8,8)
print(x)


[[1 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [1 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [1 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [1 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


In [23]:
#10) Write a program to find common values between two arrays.
#array1: [10 20 40 60]
#array2: [10, 30, 40,50]

l=[]
x=np.array([10,20,40,60])
y=np.array([10,30,40,50])
for i in x:
    for j in y:
        if(i==j):
            l.append(i)
print(l)
        

[10, 40]


In [24]:
#11) Write a program to create an array 2d array and then reshape into 1d array
l=[]
n=int(input("enter the elements range: "))
for i in range(n):
    num=int(input("enter the elements into the array: "))
    l.append(num)
m=len(l)
x=np.array(l,ndmin=2)
print(x)
print(x.reshape(m,))

enter the elements range: 4
enter the elements into the array: 2
enter the elements into the array: 3
enter the elements into the array: 4
enter the elements into the array: 5
[[2 3 4 5]]
[2 3 4 5]


In [3]:
#12) Write a user defined function for creating a 1 or 2d array from scratch without using array functions


def ndarray(x):
    n=int(input("enter the dimension: "))
    if type(x)==list or type(x)==tuple:
        c=len(x)
    if n==1:
        print("array({})".format(x))
    elif(n==0):
        m=int(l[0])
        print("array({})".format(m)) 
    elif (n==2):    
       
        if(len(x[0])>1):
            print("array([",end="")
            for i in range(c):
                print("[{}]".format(x[i]))
            print("])")
        else:
            new=[]
            for i in x:
                if (i.isdigit()):
                    z=int(i)
                    new.append(z)
            print("array([{}])".format(new)) 
    else:
        pass
l=[]
n=int(input("enter the range: "))
for i in range(n):
    num=input("enter the elements: ")
    l.append(num)
print(l)
ndarray(l)

enter the range: 3
enter the elements: 1,2,3,4
enter the elements: 2,3,4,5
enter the elements: 3,4,5,6
['1,2,3,4', '2,3,4,5', '3,4,5,6']
enter the dimension: 2
array([[1,2,3,4]
[2,3,4,5]
[3,4,5,6]
])
